# Generated by Django 4.2.28 on 2026-02-20 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pending", "0002_alter_pendinginstructor_instructor_profile"),
        (
            "accounts",
            "0002_instructor_instructorlike_instructorsubject_student_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="InstructorProfile",
        ),
        migrations.DeleteModel(
            name="StudentProfile",
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="accounts.student",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.subject"
            ),
        ),
        migrations.AddField(
            model_name="studentlike",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="accounts.instructor",
            ),
        ),
        migrations.AddField(
            model_name="studentlike",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_by",
                to="accounts.student",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instructorsubject",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="accounts.instructor",
            ),
        ),
        migrations.AddField(
            model_name="instructorsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.subject"
            ),
        ),
        migrations.AddField(
            model_name="instructorlike",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_by",
                to="accounts.instructor",
            ),
        ),
        migrations.AddField(
            model_name="instructorlike",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="accounts.student",
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
