# Generated by Django 4.2.23 on 2026-02-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentsubject",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentsubject",
            name="subject",
        ),
        migrations.AddField(
            model_name="instructor",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="instructors", to="accounts.subject"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="accounts.subject"
            ),
        ),
        migrations.DeleteModel(
            name="InstructorSubject",
        ),
        migrations.DeleteModel(
            name="StudentSubject",
        ),
    ]
