# Generated by Django 4.2.28 on 2026-03-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_user_email_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cash",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
