# Generated by Django 4.2.28 on 2026-03-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_user_cash"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="is_tutoring",
            field=models.BooleanField(default=False),
        ),
    ]
