# Generated by Django 6.0.4 on 2026-04-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_instructor_is_tutoring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
