# Generated by Django 6.0.4 on 2026-04-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
