# Generated by Django 6.0.4 on 2026-04-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_instructor_last_login_student_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("문과", "문과"),
                    ("이과", "이과"),
                    ("예체능", "예체능"),
                    ("기타", "기타"),
                ],
                max_length=10,
            ),
        ),
    ]
