# Generated by Django 6.0.4 on 2026-04-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_is_banned_user_withdraw_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
