# Generated by Django 6.0.4 on 2026-05-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_remove_user_is_banned_remove_user_withdraw_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="withdraw_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
