# Generated by Django 6.0.4 on 2026-07-05 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_user_is_banned_user_withdraw_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneverification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
