# Generated by Django 6.0.4 on 2026-08-03 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_user_profile_image"),
        ("report", "0002_inquiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSanction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("warning", "경고"),
                            ("suspension", "기간 정지"),
                            ("permanent_ban", "영구 정지"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="비우면 영구 정지", null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="제재를 발급한 관리자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sanctions_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        help_text="제재 근거가 된 신고(선택)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sanctions",
                        to="report.report",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        help_text="제재 대상 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sanctions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_user", "is_active"],
                        name="accounts_us_target__65f0a9_idx",
                    )
                ],
            },
        ),
    ]
