# Generated by Django 6.0.4 on 2026-08-28 17:34

import uuid
from django.db import migrations, models


def populate_apple_app_account_tokens(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(apple_app_account_token__isnull=True).iterator():
        user.apple_app_account_token = uuid.uuid4()
        user.save(update_fields=["apple_app_account_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_usersanction"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="apple_app_account_token",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(
            populate_apple_app_account_tokens,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="apple_app_account_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="cash_debt",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
