from django.urls import path

from .views import (
    AdminLoginAPIView,
    AdminMeAPIView,
    InstructorVerificationApproveView,
    InstructorVerificationDetailView,
    InstructorVerificationDocumentView,
    InstructorVerificationListView,
    InstructorVerificationRejectView,
    InstructorVerificationSummaryView,
    SettlementCancelView,
    SettlementCompleteView,
    SettlementDetailView,
    SettlementListView,
    SettlementSummaryView,
    TutoringRegistrationConfirmFeeView,
    TutoringRegistrationDetailView,
    TutoringRegistrationDocumentView,
    TutoringRegistrationListView,
    TutoringRegistrationRejectFeeView,
    TutoringRegistrationSummaryView,
    ReportedUserListView,
    ReportedUserSummaryView,
    ReportCaseDetailView,
    ReportCaseResolveView,
    ReportContentActionView,
    ReportSanctionView,
    ReportLiftSanctionView,
    ReportInReviewView,
    ReportEvidenceView,
    LectureReviewStreamView,
)

app_name = "adminops"

urlpatterns = [
    path("auth/login/", AdminLoginAPIView.as_view(), name="admin-login"),
    path("auth/me/", AdminMeAPIView.as_view(), name="admin-me"),
    # 학력 인증 관리
    path(
        "instructor-verifications/",
        InstructorVerificationListView.as_view(),
        name="instructor-verification-list",
    ),
    path(
        "instructor-verifications/summary/",
        InstructorVerificationSummaryView.as_view(),
        name="instructor-verification-summary",
    ),
    path(
        "instructor-verifications/<int:pk>/",
        InstructorVerificationDetailView.as_view(),
        name="instructor-verification-detail",
    ),
    path(
        "instructor-verifications/<int:pk>/approve/",
        InstructorVerificationApproveView.as_view(),
        name="instructor-verification-approve",
    ),
    path(
        "instructor-verifications/<int:pk>/reject/",
        InstructorVerificationRejectView.as_view(),
        name="instructor-verification-reject",
    ),
    path(
        "instructor-verifications/<int:pk>/documents/<int:file_id>/",
        InstructorVerificationDocumentView.as_view(),
        name="instructor-verification-document",
    ),
    # 정산 관리
    path(
        "settlements/",
        SettlementListView.as_view(),
        name="settlement-list",
    ),
    path(
        "settlements/summary/",
        SettlementSummaryView.as_view(),
        name="settlement-summary",
    ),
    path(
        "settlements/<int:pk>/",
        SettlementDetailView.as_view(),
        name="settlement-detail",
    ),
    path(
        "settlements/<int:pk>/complete/",
        SettlementCompleteView.as_view(),
        name="settlement-complete",
    ),
    path(
        "settlements/<int:pk>/cancel/",
        SettlementCancelView.as_view(),
        name="settlement-cancel",
    ),
    # 성사등록(과외 성사) 관리
    path(
        "tutoring-registrations/",
        TutoringRegistrationListView.as_view(),
        name="tutoring-registration-list",
    ),
    path(
        "tutoring-registrations/summary/",
        TutoringRegistrationSummaryView.as_view(),
        name="tutoring-registration-summary",
    ),
    path(
        "tutoring-registrations/<int:pk>/",
        TutoringRegistrationDetailView.as_view(),
        name="tutoring-registration-detail",
    ),
    path(
        "tutoring-registrations/<int:pk>/confirm-fee/",
        TutoringRegistrationConfirmFeeView.as_view(),
        name="tutoring-registration-confirm-fee",
    ),
    path(
        "tutoring-registrations/<int:pk>/reject-fee/",
        TutoringRegistrationRejectFeeView.as_view(),
        name="tutoring-registration-reject-fee",
    ),
    path(
        "tutoring-registrations/<int:pk>/documents/<int:file_id>/",
        TutoringRegistrationDocumentView.as_view(),
        name="tutoring-registration-document",
    ),
    # 신고 관리 (가해자 중심 통합 케이스)
    path(
        "reports/",
        ReportedUserListView.as_view(),
        name="report-list",
    ),
    path(
        "reports/summary/",
        ReportedUserSummaryView.as_view(),
        name="report-summary",
    ),
    path(
        "reports/users/<int:user_id>/",
        ReportCaseDetailView.as_view(),
        name="report-case-detail",
    ),
    path(
        "reports/users/<int:user_id>/resolve/",
        ReportCaseResolveView.as_view(),
        name="report-case-resolve",
    ),
    path(
        "reports/users/<int:user_id>/sanction/",
        ReportSanctionView.as_view(),
        name="report-sanction",
    ),
    path(
        "reports/users/<int:user_id>/content/",
        ReportContentActionView.as_view(),
        name="report-content-action",
    ),
    path(
        "reports/lectures/<int:lecture_id>/review-stream/",
        LectureReviewStreamView.as_view(),
        name="report-lecture-review-stream",
    ),
    path(
        "reports/sanctions/<int:sanction_id>/lift/",
        ReportLiftSanctionView.as_view(),
        name="report-lift-sanction",
    ),
    path(
        "reports/<int:pk>/in-review/",
        ReportInReviewView.as_view(),
        name="report-in-review",
    ),
    path(
        "reports/<int:pk>/evidence/",
        ReportEvidenceView.as_view(),
        name="report-evidence",
    ),
]
