# Generated by Django 6.0.4 on 2026-10-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_import_legacy_inquiries"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="supportticket",
            new_name="support_sup_status_fe88a8_idx",
            old_name="support_sup_status_84c7ee_idx",
        ),
        migrations.RenameIndex(
            model_name="supportticket",
            new_name="support_sup_assigne_6d4ffc_idx",
            old_name="support_sup_assigne_1d6bf0_idx",
        ),
        migrations.RenameIndex(
            model_name="supportticket",
            new_name="support_sup_related_e8f6f5_idx",
            old_name="support_sup_related_1869ea_idx",
        ),
    ]
