# Generated by Django 6.0.4 on 2026-10-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "support",
            "0003_rename_support_sup_status_84c7ee_idx_support_sup_status_fe88a8_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="supportticket",
            name="support_sup_assigne_6d4ffc_idx",
        ),
        migrations.AddField(
            model_name="supportticket",
            name="last_user_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="assigned_to",
        ),
    ]
