# Generated by Django 6.0.4 on 2026-10-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_home_and_mobile_images'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notice',
            new_name='notice_noti_status_b46a62_idx',
            old_name='notice_stat_publish_idx',
        ),
        migrations.RenameIndex(
            model_name='notice',
            new_name='notice_noti_exposur_4e11e8_idx',
            old_name='notice_expo_ends_idx',
        ),
    ]
