# Generated by Django 4.2.28 on 2026-02-20 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_instructor_instructorlike_instructorsubject_student_and_more",
        ),
        ("pending", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendinginstructor",
            name="instructor_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_info",
                to="accounts.instructor",
            ),
        ),
    ]
