# Generated by Django 6.0.4 on 2026-07-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pending", "0002_alter_pendinginstructor_instructor_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinginstructor",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
