# Generated by Django 6.0.4 on 2026-10-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pending", "0004_pendinginstructor_reviewed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendinginstructor",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "인증대기"),
                    ("VERIFIED", "인증완료"),
                    ("RESUBMIT_REQUIRED", "재제출 필요"),
                    ("SUSPENDED", "정지"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
