import {mkdirSync} from 'node:fs';
mkdirSync('test-results',{recursive:true});
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE});
const page=await browser.newPage({viewport:{width:1280,height:960}});
const errors=[],writes=[];page.on('pageerror',e=>errors.push(e.stack));
const lecture={id:7,title:'테스트 미적분 강의',content:'학습 목표와 기본 개념',subjects:[36],price:2000,rental_period:30,video_duration:900,instructor:{user_name:'테스트 선생님'}};
const profile={id:1,email:'test@example.invalid',nickname:'테스트 학생',role:'student',cash:5000};
await page.route('**/api/**',async route=>{
 const req=route.request(),url=new URL(req.url()),p=url.pathname.replace('/api','');let data=[];let status=200;
 if(req.method()!=='GET')writes.push({path:p,body:req.postDataJSON()});
 if(p==='/accounts/subjects/')data=[{number:36,name:'미적분 I'},{number:196,name:'Python'}];
 else if(p==='/accounts/login/')data={token:'mock-token',available_roles:[{role:'student'}]};
 else if(p==='/accounts/me/')data=profile;
 else if(p==='/lectures/')data={count:1,next:null,results:[lecture]};
 else if(p==='/lectures/7/')data={lecture_info:lecture,rental_status:'none'};
 else if(p==='/lectures/7/comments/')data=[];
 else if(p==='/lectures/7/like/')data={is_liked:true};
 else if(p==='/cash/rentals/')data={remaining_cash:3000};
 else if(p==='/chatrooms/')data=[{id:4,title:'테스트 상담',opponent_info:{user_name:'테스트 선생님'},last_message:{text:'안녕하세요'}}];
 else if(p==='/chatrooms/4/')data={id:4,title:'테스트 상담',messages:[{id:3,sender:2,sender_nickname:'선생님',text:'안녕하세요'}]};
 else if(p==='/chatrooms/4/message/')data={id:5,sender:1,sender_nickname:'테스트 학생',text:'모의 전송'};
 else if(p==='/tutoring/instructors/')data=[{id:9,user_name:'테스트 선생님',university:'테스트 대학',subjects:[36],is_certified:true}];
 else if(p==='/tutoring/instructors/9/')data={id:9,user_name:'테스트 선생님',subjects:[36]};
 else if(p==='/tutoring/instructors/9/info/')data={instruction:'수업 소개',cost_display:'협의 후 결정'};
 else if(p==='/tutoring/my-posts/')data=[{id:11,title:'테스트 공고',is_active:true}];
 else if(p==='/tutoring/propose-to-instructor/')data={room_id:4};
 await route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
});
await page.goto('http://127.0.0.1:4173');
await page.getByRole('button',{name:'로그인',exact:true}).first().click();
await page.getByLabel('이메일',{exact:true}).fill('test@example.invalid');
await page.getByLabel('비밀번호',{exact:true}).fill('mock');
await page.getByRole('dialog').getByRole('button',{name:'로그인',exact:true}).click();
await page.getByRole('heading',{name:'테스트 학생님, 반가워요.'}).waitFor();
await page.getByRole('link',{name:'강의',exact:true}).click();
await page.getByRole('heading',{name:'테스트 미적분 강의'}).waitFor();
await page.getByRole('textbox',{name:'검색',exact:true}).fill('미적분');
const request=page.waitForRequest(r=>r.url().includes('/api/lectures/')&&r.url().includes('q='));
await page.getByRole('button',{name:'검색',exact:true}).click();
assert.equal(new URL((await request).url()).searchParams.get('q'),'미적분');
await page.screenshot({path:'test-results/redesign-lectures-desktop.png',fullPage:true});
await page.getByRole('heading',{name:'테스트 미적분 강의'}).click();
await page.screenshot({path:'test-results/redesign-detail-desktop.png'});
await page.getByRole('button',{name:'찜하기',exact:true}).click();
await page.getByRole('button',{name:'캐시로 대여',exact:true}).click();
assert.equal(writes.filter(w=>w.path==='/cash/rentals/').length,0);
await page.getByRole('button',{name:'대여 확정',exact:true}).click();
await page.getByText('강의를 대여했습니다.',{exact:true}).first().waitFor();
assert.deepEqual(writes.find(w=>w.path==='/cash/rentals/').body,{lecture_id:7});
await page.keyboard.press('Escape');
await page.getByRole('link',{name:'채팅',exact:true}).click();
await page.getByRole('button',{name:/테스트 선생님/}).click();
assert.equal(await page.getByLabel('대화 이미지 첨부').count(),0);
await page.getByRole('textbox',{name:'메시지',exact:true}).fill('모의 전송');
await page.getByRole('button',{name:'메시지 보내기',exact:true}).click();
await page.getByText('모의 전송',{exact:true}).waitFor({timeout:7000}).catch(async e=>{console.log(JSON.stringify({writes,errors,text:await page.locator('body').innerText()}));await page.screenshot({path:'test-results/chat-error.png'});throw e;});
assert.deepEqual(writes.find(w=>w.path==='/chatrooms/4/message/').body,{text:'모의 전송'});
await page.getByRole('navigation',{name:'주요 메뉴',exact:true}).getByRole('link',{name:'과외',exact:true}).click();
await page.getByRole('button',{name:'테스트 선생님 선생님 프로필',exact:true}).click();
await page.getByRole('button',{name:'과외 상담 제안하기'}).click();
await page.getByLabel('상담할 내 과외 공고').selectOption('11');
await page.getByRole('button',{name:'제안 보내기',exact:true}).click();
await page.getByRole('heading',{name:'채팅',exact:true}).waitFor();
assert.deepEqual(writes.find(w=>w.path==='/tutoring/propose-to-instructor/').body,{instructor_id:9,post_id:11});
await page.goto('http://127.0.0.1:4173/#profile');
await page.getByRole('heading',{name:'내 정보 수정'}).waitFor();
await page.screenshot({path:'test-results/redesign-profile-desktop.png',fullPage:true});
assert.deepEqual(errors,[]);
console.log('PASS mocked login, lecture search q, rental explicit confirmation, likes, chat send, tutoring proposal; no real writes');
await browser.close();
