# Generated by Django 6.0.4 on 2026-06-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="is_chat_active",
            field=models.BooleanField(default=True),
        ),
    ]
