# Generated by Django 4.2.28 on 2026-03-08 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("apple", "Apple"), ("google", "Google")],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="결제 플랫폼 고유 트랜잭션 ID", max_length=255, unique=True
                    ),
                ),
                ("purchased_cash", models.PositiveIntegerField()),
                ("paid_amount", models.PositiveIntegerField()),
                ("fee_deducted_amount", models.PositiveIntegerField()),
                ("remaining_cash", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
