# Generated by Django 4.2.28 on 2026-03-11 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lecture", "0003_lecture_rental_period"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasehistory",
            name="is_refunded",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="LectureRentalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased_cash", models.PositiveIntegerField()),
                ("remaining_cash", models.PositiveIntegerField()),
                ("is_canceled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to="lecture.lecture",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_rentals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
