# Generated by Django 4.2.28 on 2026-03-12 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_instructor_is_tutoring"),
        ("cash", "0002_purchasehistory_is_refunded_lecturerentalhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorMonthlyRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("total_cash", models.PositiveIntegerField(default=0)),
                ("rank", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_ranks",
                        to="accounts.instructor",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "rank"],
                "unique_together": {("year", "month", "instructor")},
            },
        ),
    ]
