# Generated by Django 4.2.28 on 2026-03-12 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_instructor_is_tutoring"),
        ("cash", "0003_instructormonthlyrank"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturerentalhistory",
            name="is_settled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SettlementRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "대기"), ("COMPLETED", "정산완료")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="accounts.instructor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=100)),
                ("account_holder", models.CharField(max_length=100)),
                (
                    "instructor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="accounts.instructor",
                    ),
                ),
            ],
        ),
    ]
