# Generated by Django 6.0.4 on 2026-07-16 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash", "0006_lecturerentalhistory_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturerentalhistory",
            name="settlement",
            field=models.ForeignKey(
                blank=True,
                help_text="이 대여가 귀속된 정산 신청 건. 과거 데이터는 null일 수 있다.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rentals",
                to="cash.settlementrecord",
            ),
        ),
        migrations.AddField(
            model_name="settlementrecord",
            name="admin_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="settlementrecord",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="settlementrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "대기"),
                    ("COMPLETED", "정산완료"),
                    ("CANCELED", "정산취소"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
