# Generated by Django 6.0.4 on 2026-07-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash", "0007_lecturerentalhistory_settlement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlementrecord",
            name="payment_reference",
            field=models.CharField(
                blank=True, default="", help_text="지급(송금) 참조번호", max_length=100
            ),
        ),
    ]
