# Generated by Django 6.0.4 on 2026-08-28 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cash", "0008_settlementrecord_payment_reference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppStoreWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_uuid", models.UUIDField(unique=True)),
                (
                    "notification_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("subtype", models.CharField(blank=True, default="", max_length=50)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("payload_sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "수신"),
                            ("PROCESSED", "처리 완료"),
                            ("IGNORED", "처리 대상 아님"),
                            ("FAILED", "처리 실패"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="app_account_token",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="environment",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="original_transaction_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="price_milliunits",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="product_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="purchase_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="refund_debt",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="refund_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="refunded_cash",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="storefront",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddIndex(
            model_name="purchasehistory",
            index=models.Index(
                fields=["platform", "created_at"],
                name="cash_ph_platform_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasehistory",
            constraint=models.CheckConstraint(
                condition=models.Q(("refund_percentage__lte", 100000)),
                name="cash_purchase_refund_pct_lte_100000",
            ),
        ),
    ]
