# Generated by Django 4.2.28 on 2026-03-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture", "0002_searchhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="rental_period",
            field=models.PositiveIntegerField(default=30, help_text="대여 기간 (일)"),
        ),
    ]
