# Generated by Django 4.2.28 on 2026-03-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture", "0003_lecture_rental_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lecture",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
    ]
