# Generated by Django 6.0.4 on 2026-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0005_lecture_video_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
