# Generated by Django 6.0.4 on 2026-07-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0007_lecture_suspended_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
    ]
