# Generated by Codex on 2026-10-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("lecture", "0009_comment_blocked_at_comment_blocked_by_and_more")]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="sample_preview",
            field=models.FileField(blank=True, null=True, upload_to="lectures/sample_previews/"),
        ),
        migrations.AddField(
            model_name="lecture",
            name="sample_preview_duration",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
