# Generated by Django 6.0.4 on 2026-04-15 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="muted_by",
            field=models.ManyToManyField(
                blank=True, related_name="muted_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
