# Generated by Django 6.0.4 on 2026-05-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0003_add_chatroom_accept_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdevicetoken",
            name="is_chat_active",
            field=models.BooleanField(default=True),
        ),
    ]
