# Generated by Django 6.0.4 on 2026-06-30 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0004_userdevicetoken_is_chat_active"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="blockeduser",
            name="unique_block",
        ),
        migrations.DeleteModel(
            name="BlockedUser",
        ),
    ]
