# Generated by Django 4.2.23 on 2026-02-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_studentsubject_student_and_more"),
        ("tutoring", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructorinfosubject",
            name="instructor_Info",
        ),
        migrations.RemoveField(
            model_name="instructorinfosubject",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="instructorreviewsubject",
            name="instructor_review",
        ),
        migrations.RemoveField(
            model_name="instructorreviewsubject",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="tutoringpostregion",
            name="region",
        ),
        migrations.RemoveField(
            model_name="tutoringpostregion",
            name="tutoring_posts",
        ),
        migrations.RemoveField(
            model_name="tutoringpostsubject",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="tutoringpostsubject",
            name="tutoring_post",
        ),
        migrations.AddField(
            model_name="instructorinfo",
            name="regions",
            field=models.ManyToManyField(
                blank=True, related_name="instructor_infos", to="tutoring.region"
            ),
        ),
        migrations.AddField(
            model_name="instructorinfo",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="instructor_infos", to="accounts.subject"
            ),
        ),
        migrations.AddField(
            model_name="instructorreview",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="instructor_reviews", to="accounts.subject"
            ),
        ),
        migrations.AddField(
            model_name="tutoringpost",
            name="regions",
            field=models.ManyToManyField(
                blank=True, related_name="tutoring_posts", to="tutoring.region"
            ),
        ),
        migrations.AddField(
            model_name="tutoringpost",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="tutoring_posts", to="accounts.subject"
            ),
        ),
        migrations.DeleteModel(
            name="InstructorInfoRegion",
        ),
        migrations.DeleteModel(
            name="InstructorInfoSubject",
        ),
        migrations.DeleteModel(
            name="InstructorReviewSubject",
        ),
        migrations.DeleteModel(
            name="TutoringPostRegion",
        ),
        migrations.DeleteModel(
            name="TutoringPostSubject",
        ),
    ]
