# Generated by Django 4.2.28 on 2026-02-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutoring", "0002_remove_instructorinfosubject_instructor_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutoringpost",
            name="region",
        ),
        migrations.RemoveField(
            model_name="tutoringpost",
            name="title",
        ),
        migrations.AddField(
            model_name="tutoringpost",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
