# Generated by Django 4.2.23 on 2026-03-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tutoring",
            "0003_remove_tutoringpost_region_remove_tutoringpost_title_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructorreview",
            name="rating",
        ),
        migrations.AddField(
            model_name="instructorreview",
            name="professionalism",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instructorreview",
            name="punctuality",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instructorreview",
            name="teaching_skill",
            field=models.IntegerField(default=0),
        ),
    ]
