# Generated by Django 4.2.23 on 2026-03-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutoring", "0004_remove_instructorreview_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringpost",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutoringpost",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("유치원생", "유치원생"),
                    ("초1", "초1"),
                    ("초2", "초2"),
                    ("초3", "초3"),
                    ("초4", "초4"),
                    ("초5", "초5"),
                    ("초6", "초6"),
                    ("중1", "중1"),
                    ("중2", "중2"),
                    ("중3", "중3"),
                    ("고1", "고1"),
                    ("고2", "고2"),
                    ("고3", "고3"),
                    ("재수생", "재수생"),
                    ("사회인", "사회인"),
                ],
                max_length=20,
            ),
        ),
    ]
