# Generated by Django 4.2.23 on 2026-03-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_user_email_alter_user_phone"),
        ("tutoring", "0005_tutoringpost_age_tutoringpost_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutoringResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "class_type",
                    models.CharField(
                        blank=True,
                        choices=[("단기 수업", "단기 수업"), ("장기 수업", "장기 수업")],
                        max_length=20,
                    ),
                ),
                ("first_month_fee", models.IntegerField(blank=True, null=True)),
                ("payback_bank", models.CharField(blank=True, max_length=50)),
                ("payback_account_number", models.CharField(blank=True, max_length=50)),
                ("payback_account_holder", models.CharField(blank=True, max_length=50)),
                ("instructor_bank", models.CharField(blank=True, max_length=50)),
                (
                    "instructor_account_number",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "instructor_account_holder",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "fee_confirmation_file",
                    models.FileField(
                        blank=True, null=True, upload_to="fee_confirmations/"
                    ),
                ),
                ("is_student_confirmed", models.BooleanField(default=False)),
                ("is_instructor_confirmed", models.BooleanField(default=False)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutoring_resources",
                        to="accounts.instructor",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutoring_resources",
                        to="accounts.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutoring_resources",
                        to="accounts.subject",
                    ),
                ),
            ],
        ),
    ]
