# Generated by Django 4.2.23 on 2026-03-06 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutoring", "0006_tutoringresource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutoringresource",
            name="instructor_account_holder",
        ),
        migrations.RemoveField(
            model_name="tutoringresource",
            name="instructor_account_number",
        ),
        migrations.RemoveField(
            model_name="tutoringresource",
            name="instructor_bank",
        ),
    ]
