# Generated by Django 4.2.28 on 2026-03-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_instructor_is_tutoring"),
        ("tutoring", "0007_remove_tutoringresource_instructor_account_holder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutoringPostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_likes",
                        to="accounts.instructor",
                    ),
                ),
                (
                    "tutoring_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_by",
                        to="tutoring.tutoringpost",
                    ),
                ),
            ],
            options={
                "unique_together": {("instructor", "tutoring_post")},
            },
        ),
    ]
