# Generated by Django 4.2.28 on 2026-03-12 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutoring", "0008_tutoringpostlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringpost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 3, 12, 15, 18, 22, 517728, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
