# Generated by Django 6.0.4 on 2026-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0009_tutoringpost_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorreview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="instructorinfo",
            name="method",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
