# Generated by Django 6.0.4 on 2026-04-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0009_tutoringpost_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringpost",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
