# Generated by Django 6.0.4 on 2026-04-22 17:52

import config.apps.tutoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0010_instructorreview_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorinfo",
            name="method",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[config.apps.tutoring.models.validate_method],
            ),
        ),
        migrations.AlterField(
            model_name="tutoringpost",
            name="method",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[config.apps.tutoring.models.validate_method],
            ),
        ),
    ]
