# Generated by Django 6.0.4 on 2026-04-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0011_alter_instructorinfo_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringpost",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
