# Generated by Django 6.0.4 on 2026-04-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0012_tutoringpost_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentreview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="tutoringpost",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("유치원생", "유치원생"),
                    ("초1", "초1"),
                    ("초2", "초2"),
                    ("초3", "초3"),
                    ("초4", "초4"),
                    ("초5", "초5"),
                    ("초6", "초6"),
                    ("중1", "중1"),
                    ("중2", "중2"),
                    ("중3", "중3"),
                    ("고1", "고1"),
                    ("고2", "고2"),
                    ("고3", "고3"),
                    ("N수생", "N수생"),
                    ("재수생", "재수생"),
                    ("대학생", "대학생"),
                    ("사회인", "사회인"),
                ],
                max_length=20,
            ),
        ),
    ]
