# Generated by Django 6.0.4 on 2026-04-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0014_tutoringresource_fee_payment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutoringResourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="fee_confirmations/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tutoring_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="tutoring.tutoringresource",
                    ),
                ),
            ],
        ),
    ]
