# Generated by Django 6.0.4 on 2026-07-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_alter_phoneverification_user"),
        ("tutoring", "0015_tutoringresourcefile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutoringresource",
            name="subject",
        ),
        migrations.AddField(
            model_name="tutoringresource",
            name="subject",
            field=models.ManyToManyField(
                blank=True, related_name="tutoring_resources", to="accounts.subject"
            ),
        ),
    ]
