# Generated by Django 6.0.4 on 2026-07-12 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0005_remove_blockeduser_unique_block_delete_blockeduser"),
        ("tutoring", "0016_remove_tutoringresource_subject_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TossWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_key", models.CharField(max_length=200, unique=True)),
                ("order_id", models.CharField(max_length=64)),
                ("event_status", models.CharField(max_length=30)),
                ("payload", models.JSONField()),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TutoringRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                (
                    "attribute_validation_status",
                    models.CharField(
                        choices=[
                            ("UNCHECKED", "미확인"),
                            ("MATCHED", "일치"),
                            ("MISMATCHED", "불일치"),
                        ],
                        default="UNCHECKED",
                        max_length=20,
                    ),
                ),
                (
                    "contract_status",
                    models.CharField(
                        choices=[
                            ("COLLECTING", "계약 정보 수집 중"),
                            ("REGISTERED", "등록 완료"),
                            ("ACTIVE", "과외 진행 중"),
                            ("CANCELLED", "취소"),
                        ],
                        default="COLLECTING",
                        max_length=20,
                    ),
                ),
                ("confirmed_class_type", models.CharField(blank=True, max_length=20)),
                (
                    "confirmed_first_month_fee",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("terms_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat_room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutoring_registration",
                        to="chat_app.chatroom",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instructor_tutoring_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_tutoring_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentPaybackAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_code", models.CharField(max_length=20)),
                ("encrypted_account_number", models.TextField()),
                ("account_holder", models.CharField(max_length=30)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "미인증"),
                            ("VERIFIED", "인증 완료"),
                            ("FAILED", "인증 실패"),
                        ],
                        default="UNVERIFIED",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_payback_account",
                        to="tutoring.tutoringregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommissionInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("INITIAL", "최초 수수료"), ("ADJUSTMENT", "추가 정산")],
                        default="INITIAL",
                        max_length=20,
                    ),
                ),
                ("base_amount", models.PositiveBigIntegerField()),
                ("commission_rate_bps", models.PositiveIntegerField()),
                ("commission_amount", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "결제 준비"),
                            ("PAYMENT_PENDING", "입금 대기"),
                            ("PAID", "납부 완료"),
                            ("FAILED", "결제 실패"),
                            ("CANCELLED", "취소"),
                        ],
                        default="READY",
                        max_length=30,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_invoices",
                        to="tutoring.tutoringregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutoringSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("STUDENT", "학생"), ("INSTRUCTOR", "강사")], max_length=20
                    ),
                ),
                (
                    "class_type",
                    models.CharField(
                        choices=[("REGULAR", "정규 수업"), ("SHORT_TERM", "단기 수업")],
                        max_length=20,
                    ),
                ),
                ("first_month_fee", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="tutoring.tutoringregistration",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutoring_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VirtualAccountPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=64, unique=True)),
                (
                    "payment_key",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("expected_amount", models.PositiveBigIntegerField()),
                ("bank_code", models.CharField(blank=True, max_length=20)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("account_holder", models.CharField(blank=True, max_length=100)),
                ("toss_secret", models.TextField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fee_payment_status",
                    models.CharField(
                        choices=[
                            ("ISSUING", "가상계좌 발급 중"),
                            ("WAITING_FOR_DEPOSIT", "입금 대기"),
                            ("DONE", "납부 완료"),
                            ("FAILED", "결제 처리 실패"),
                            ("EXPIRED", "입금 기한 만료"),
                            ("CANCELLED", "결제 취소"),
                        ],
                        default="ISSUING",
                        max_length=30,
                    ),
                ),
                ("toss_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_account_payments",
                        to="tutoring.commissioninvoice",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="commissioninvoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_type", "INITIAL")),
                fields=("registration",),
                name="unique_initial_commission_invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="tutoringsubmission",
            constraint=models.UniqueConstraint(
                fields=("registration", "role"),
                name="unique_tutoring_submission_per_role",
            ),
        ),
    ]
