# Generated by Django 6.0.4 on 2026-07-15 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0017_tosswebhookevent_tutoringregistration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringproposal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 7, 15, 11, 43, 47, 865957, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
