# Generated by Django 6.0.4 on 2026-07-25 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_email", models.EmailField(blank=True, max_length=254)),
                ("action", models.CharField(db_index=True, max_length=100)),
                (
                    "target_type",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "target_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="adminops_ad_target__4ce8ce_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="adminops_ad_action_22bede_idx",
                    ),
                ],
            },
        ),
    ]
