# Generated by Django 4.2.28 on 2026-03-11 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_image",
                    models.ImageField(
                        blank=True,
                        help_text="증거 이미지 (선택)",
                        null=True,
                        upload_to="reports/evidence/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported_user",
                    models.ForeignKey(
                        help_text="신고 대상 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="신고한 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        choices=[
                            ("inappropriate_content", "부적절한 내용"),
                            ("false_information", "허위 정보 기재"),
                            ("abusive_language", "비속어/폭언"),
                            ("excessive_request", "불합리한/과도한 요구/요청"),
                            ("unreported_class_completion", "수업 성사 미신고"),
                            ("other", "기타"),
                        ],
                        help_text="신고 사유",
                        max_length=50,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="report.report",
                    ),
                ),
            ],
            options={
                "unique_together": {("report", "content")},
            },
        ),
    ]
