# Generated by Django 6.0.4 on 2026-08-03 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("report", "0002_inquiry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="description",
            field=models.TextField(blank=True, help_text="신고자가 남긴 자유서술"),
        ),
        migrations.AddField(
            model_name="report",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="resolution_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="report",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="처리한 관리자",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_resolved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="source",
            field=models.CharField(
                choices=[
                    ("teacher_profile", "강사 프로필"),
                    ("chat", "채팅"),
                    ("lecture", "영상(강의)"),
                    ("comment", "댓글"),
                    ("tutoring_post", "과외 공고"),
                ],
                db_index=True,
                default="teacher_profile",
                help_text="신고 맥락(강사프로필/채팅/영상/댓글/공고)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "미처리"),
                    ("in_review", "보류(검토중)"),
                    ("resolved", "조치완료"),
                    ("dismissed", "무혐의(기각)"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reported_user",
            field=models.ForeignKey(
                help_text="신고 대상 사용자(콘텐츠 신고는 소유자로 도출)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["reported_user", "status"],
                name="report_repo_reporte_15d051_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="report_repo_content_7ea2c7_idx",
            ),
        ),
    ]
